fixing: src/components/ImgSkeleton.tsx(1,20): error TS6133: 'useEffect' is declared but its value is never read. src/components/ImgSkeleton.tsx(15,11): error TS6133: 'image' is declared but its value is never read.